export const MAZE_GAME_TITLE = 'Labirinto do Professor: Caçada ao Ponto Dourado';

export const MAZE_GAME_DESCRIPTION = 'Até 50 alunos entram no labirinto ao vivo para cercar o Ponto Dourado (professor). Todos têm a mesma velocidade, podem coletar pílulas de velocidade, e o professor prepara blocos temporários e abre caminhos destruindo paredes.';

export const MAZE_GAME_TEMPLATE = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
*{box-sizing:border-box}body{margin:0;overflow:hidden;background:#090b1a;color:#fff;font-family:system-ui,sans-serif;touch-action:none}canvas{width:100vw;height:100vh;display:block}.hud{position:fixed;inset:0;pointer-events:none}.panel{pointer-events:auto;position:absolute;top:14px;left:14px;max-width:350px;padding:14px 16px;background:#121735e8;border:1px solid #5964c999;border-radius:16px;box-shadow:0 12px 35px #0008}.panel h1{font-size:17px;margin:0 0 5px;color:#ffe670}.panel p{font-size:12px;line-height:1.35;margin:4px 0;color:#cbd2ff}.right{left:auto;right:14px;text-align:right}.count{font-size:28px;font-weight:900;color:#fff}.tag{display:inline-block;padding:3px 8px;border-radius:30px;background:#27307a;font-size:11px;font-weight:700}select,button{font:inherit;border:0;border-radius:9px;padding:8px 10px;margin:5px 3px 0 0}button{background:#ffe670;color:#302600;font-weight:800;cursor:pointer}button:hover{background:#fff0a0}.message{position:absolute;inset:0;display:grid;place-items:center;text-align:center;background:#080a1dc7;padding:24px}.message div{max-width:540px;padding:28px;background:#171d45;border:1px solid #6975e8;border-radius:22px}.message h2{font-size:30px;margin:0 0 8px;color:#ffe670}.hide{display:none}.help{position:absolute;bottom:14px;left:14px;font-size:11px;color:#cbd2ff;background:#121735d9;padding:8px 11px;border-radius:10px}.touch-controls{display:none}@media (pointer:coarse),(max-width:700px){.panel{max-width:245px;padding:10px 12px}.panel h1{font-size:14px}.panel p{font-size:11px}.right{max-width:106px;padding:9px 10px}.count{font-size:22px}.help{bottom:151px;max-width:calc(100vw - 28px)}.touch-controls{display:block;pointer-events:auto;position:absolute;inset:auto 0 14px 0}.pad{position:absolute;left:16px;bottom:0;display:grid;grid-template-columns:repeat(3,58px);grid-template-rows:repeat(2,54px);gap:4px}.touch-controls button{width:58px;height:54px;margin:0;padding:0;background:#1e2869e8;color:#fff;border:1px solid #8392ff;border-radius:16px;font-size:25px;box-shadow:0 5px 16px #0008;touch-action:none;user-select:none}.touch-controls button:active,.touch-controls button.pressed{background:#6574ec}.touch-controls .up{grid-column:2}.touch-controls .left{grid-column:1;grid-row:2}.touch-controls .down{grid-column:2;grid-row:2}.touch-controls .right{grid-column:3;grid-row:2}.touch-controls .shoot{position:absolute;right:18px;bottom:8px;width:74px;height:74px;border-radius:50%;background:#ffe670;color:#4a3500;border-color:#fff3a3;font-size:24px}.message{padding:16px}.message div{padding:22px}.message h2{font-size:25px}}
</style></head><body><canvas id="maze"></canvas><div class="hud"><div class="panel"><h1>🌀 Labirinto do Professor</h1><span id="role" class="tag"></span><p id="status">Conectando à arena...</p><div id="hostControls" class="hide"><select id="duration"><option value="120">2 minutos</option><option value="180">3 minutos</option><option value="300">5 minutos</option><option value="600">10 minutos</option></select><button id="start">Iniciar caçada</button></div></div><div class="panel right"><div class="count" id="timer">--:--</div><p id="online">0 caçadores no labirinto</p></div><div class="help" id="help"></div><div id="touchControls" class="touch-controls"><div class="pad"><button class="up" data-key="w">▲</button><button class="left" data-key="a">◀</button><button class="down" data-key="s">▼</button><button class="right" data-key="d">▶</button></div><button id="touchAction" class="shoot" data-key=" ">✦</button></div><div id="message" class="message"><div><h2>Preparando o labirinto...</h2><p>Conectando todos os pontos aventureiros.</p></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script>
(() => {
const cfg=window.__EDUCATIONAL_GAME_CONFIG__||{}, isHost=cfg.role==='teacher', room=cfg.roomId||'demo', W=80,H=55,S=32;
const canvas=document.querySelector('#maze'),ctx=canvas.getContext('2d'), status=document.querySelector('#status'), msg=document.querySelector('#message'), timer=document.querySelector('#timer'), online=document.querySelector('#online'),hostControls=document.querySelector('#hostControls');
document.querySelector('#role').textContent=isHost?'⭐ VOCÊ É O PONTO DOURADO':'👾 VOCÊ É UM CAÇADOR';document.querySelector('#help').textContent=isHost?'Mover: WASD ou setas • Preparar bloco: Espaço/clique • Destruir parede: Ctrl':'Mover: WASD ou setas • Disparar: Espaço ou clique • Frutas recuperam 1 coração';
if(isHost){hostControls.classList.remove('hide');document.querySelector('#touchAction').textContent='▦'}
const rand=(n)=>{let x=Math.sin(n*912.17)*10000;return x-Math.floor(x)}, walls=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1||rand(x*31+y*97)>.73));
for(let y=25;y<30;y++)for(let x=38;x<43;x++)walls[y][x]=false;
const open=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(!walls[y][x])open.push({x:(x+.5)*S,y:(y+.5)*S});
const pick=(salt)=>open[Math.floor(rand(salt)*open.length)], self={id:crypto.randomUUID(),name:isHost?'Professor Dourado':(prompt('Como os outros caçadores devem chamar você?','Ninja do Labirinto')||'Ninja do Labirinto').slice(0,22),x:(40.5)*S,y:(27.5)*S,alive:true,hearts:isHost?0:3,speedUntil:0,color:isHost?'#ffe670':'#f472b6'};
if(!isHost){const p=pick(Date.now());self.x=p.x;self.y=p.y}let players={[self.id]:self},bullets=[],blocks={},fruits={},pills={},keys={},startedAt=0,duration=120,finished=false,lastSend=0,lastAction=0,lastWallShot=0,nextFruitAt=0,nextPillAt=0,lastMove={dx:1,dy:0},pendingBlock=null;
const blockKey=(x,y)=>x+':'+y, safe=(x,y)=>{let gx=Math.floor(x/S),gy=Math.floor(y/S),block=blocks[blockKey(gx,gy)];return gx>0&&gy>0&&gx<W-1&&gy<H-1&&!walls[gy][gx]&&(!block||block.until<=Date.now())};
const show=(title,text,button)=>{msg.classList.remove('hide');msg.innerHTML='<div><h2>'+title+'</h2><p>'+text+'</p>'+ (button||'')+'</div>'};const hide=()=>msg.classList.add('hide');
show(isHost?'Sua arena está pronta':'Entrando na caçada...',isHost?'Compartilhe o QR Code/link e escolha o tempo para iniciar.':'Aguarde o professor iniciar a partida.');
let channel;const emit=(event,payload)=>channel&&channel.send({type:'broadcast',event,payload}).catch(()=>{});
const start=(data)=>{startedAt=data.startedAt;duration=data.duration;finished=false;self.alive=true;self.hearts=isHost?0:3;self.speedUntil=0;players[self.id]=self;blocks={};fruits={};pills={};pendingBlock=null;nextFruitAt=Date.now()+6000+Math.random()*5000;nextPillAt=Date.now()+8000+Math.random()*6000;if(isHost)hostControls.classList.add('hide');hide();status.textContent=isHost?'Corra, professor! Prepare o bloco e saia da célula para ativá-lo.':'Encontre o Ponto Dourado e colete frutas e pílulas!'};
const end=(win,reason)=>{if(finished)return;finished=true;emit('end',{win,reason});if(isHost)hostControls.classList.remove('hide');show(win?'🏆 O professor venceu!':'💥 O professor foi pego!',reason);status.textContent='Partida encerrada.'};
if(!cfg.supabaseUrl||!cfg.anonKey||!window.supabase){show('Configuração pendente','Este jogo precisa ser aberto pelo portal para conectar ao Supabase.');return}
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.anonKey), name='maze-'+room;
channel=client.channel(name,{config:{broadcast:{self:false,ack:false}}}).on('broadcast',{event:'state'},({payload})=>{if(payload.id!==self.id)players[payload.id]={...players[payload.id],...payload}}).on('broadcast',{event:'start'},({payload})=>start(payload)).on('broadcast',{event:'request'},()=>{if(isHost&&startedAt&&!finished)emit('start',{startedAt,duration})}).on('broadcast',{event:'shot'},({payload})=>{bullets.push(payload)}).on('broadcast',{event:'block'},({payload})=>{blocks[blockKey(payload.x,payload.y)]=payload}).on('broadcast',{event:'wallDestroyed'},({payload})=>{if(payload.x>0&&payload.y>0&&payload.x<W-1&&payload.y<H-1)walls[payload.y][payload.x]=false}).on('broadcast',{event:'fruit'},({payload})=>{fruits[payload.id]=payload}).on('broadcast',{event:'fruitCollected'},({payload})=>{delete fruits[payload.fruitId];if(players[payload.playerId])players[payload.playerId].hearts=payload.hearts;if(payload.playerId===self.id){self.hearts=payload.hearts;status.textContent='🍎 Fruta coletada! Agora você tem '+payload.hearts+' corações.'}}).on('broadcast',{event:'pill'},({payload})=>{pills[payload.id]=payload}).on('broadcast',{event:'pillCollected'},({payload})=>{delete pills[payload.pillId];if(players[payload.playerId])players[payload.playerId].speedUntil=payload.speedUntil;if(payload.playerId===self.id){self.speedUntil=payload.speedUntil;status.textContent='💊 Velocidade dobrada por 6 segundos!'}}).on('broadcast',{event:'damage'},({payload})=>{const target=players[payload.id];if(target)target.hearts=payload.hearts;if(payload.id===self.id){self.hearts=payload.hearts;status.textContent='Você foi atingido! Restam '+payload.hearts+' corações.'}}).on('broadcast',{event:'eliminate'},({payload})=>{if(players[payload.id])players[payload.id].alive=false;if(payload.id===self.id){self.alive=false;show('🎯 Você perdeu todos os corações!',payload.reason+' Você pode assistir ao restante da rodada.')}}).on('broadcast',{event:'end'},({payload})=>{if(!finished){finished=true;if(isHost)hostControls.classList.remove('hide');show(payload.win?'🏆 O professor venceu!':'💥 O professor foi pego!',payload.reason)}}).subscribe(s=>{if(s==='SUBSCRIBED'){status.textContent=isHost?'Pronto para começar.':'Conectado! Aguardando o professor.';emit('request',{})}});
document.querySelector('#start').onclick=()=>{duration=Number(document.querySelector('#duration').value);start({startedAt:Date.now(),duration});emit('start',{startedAt,duration})};
addEventListener('keydown',e=>{let key=e.key.toLowerCase();keys[key]=true;if(e.ctrlKey||[' ','control','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();if(!e.repeat&&(key===' '||key==='enter'))useAction();if(!e.repeat&&key==='control')shootWallBreaker()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.onclick=()=>useAction();document.querySelectorAll('#touchControls button[data-key]').forEach(button=>{const key=button.dataset.key,release=e=>{keys[key]=false;button.classList.remove('pressed');try{button.releasePointerCapture(e.pointerId)}catch(_){}};button.addEventListener('pointerdown',e=>{e.preventDefault();keys[key]=true;button.classList.add('pressed');button.setPointerCapture(e.pointerId);if(key===' ')useAction()});button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release)});
function direction(){let dx=keys['a']||keys['arrowleft']?-1:keys['d']||keys['arrowright']?1:0,dy=keys['w']||keys['arrowup']?-1:keys['s']||keys['arrowdown']?1:0;if(!dx&&!dy)dx=1;return {dx,dy}}
function useAction(){if(!startedAt||finished||!self.alive||Date.now()-lastAction<360)return;lastAction=Date.now();if(isHost){let x=Math.floor(self.x/S),y=Math.floor(self.y/S),key=blockKey(x,y);if(walls[y][x]||blocks[key])return;pendingBlock={x,y};status.textContent='Bloco preparado! Saia desta célula para ativá-lo.';return}let {dx,dy}=direction(),length=Math.hypot(dx,dy),b={id:crypto.randomUUID(),x:self.x,y:self.y,dx:dx/length,dy:dy/length,owner:self.id,life:42};bullets.push(b);emit('shot',b)}
function activatePendingBlock(){if(!pendingBlock)return;let {x,y}=pendingBlock,key=blockKey(x,y);pendingBlock=null;if(walls[y][x]||blocks[key])return;let payload={x,y,until:Date.now()+9000};blocks[key]=payload;emit('block',payload);status.textContent='Bloco ativado na posição que você deixou! Ele dura 9 segundos.'}
function shootWallBreaker(){let now=Date.now();if(!isHost||!startedAt||finished||!self.alive||now-lastWallShot<420)return;lastWallShot=now;let length=Math.hypot(lastMove.dx,lastMove.dy),b={id:crypto.randomUUID(),x:self.x,y:self.y,dx:lastMove.dx/length,dy:lastMove.dy/length,owner:self.id,life:48,wallBreaker:true};bullets.push(b);emit('shot',b);status.textContent='Disparo quebra-parede lançado!'}
function spawnFruit(){let spot=pick(Date.now()+Math.random()*100000),gx=Math.floor(spot.x/S),gy=Math.floor(spot.y/S);if(blocks[blockKey(gx,gy)]||Object.values(fruits).some(f=>Math.hypot(f.x-spot.x,f.y-spot.y)<S))return;let fruit={id:crypto.randomUUID(),x:spot.x,y:spot.y,until:Date.now()+14000};fruits[fruit.id]=fruit;emit('fruit',fruit)}
function spawnPill(){let spot=pick(Date.now()+Math.random()*200000),gx=Math.floor(spot.x/S),gy=Math.floor(spot.y/S);if(blocks[blockKey(gx,gy)]||Object.values(fruits).some(f=>Math.hypot(f.x-spot.x,f.y-spot.y)<S)||Object.values(pills).some(p=>Math.hypot(p.x-spot.x,p.y-spot.y)<S))return;let pill={id:crypto.randomUUID(),x:spot.x,y:spot.y,until:Date.now()+14000};pills[pill.id]=pill;emit('pill',pill)}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function update(){let now=Date.now();Object.keys(blocks).forEach(key=>{if(blocks[key].until<=now)delete blocks[key]});Object.keys(fruits).forEach(key=>{if(fruits[key].until<=now)delete fruits[key]});Object.keys(pills).forEach(key=>{if(pills[key].until<=now)delete pills[key]});if(startedAt&&!finished){let left=Math.max(0,duration-(now-startedAt)/1000);timer.textContent=Math.floor(left/60)+':'+String(Math.ceil(left%60)).padStart(2,'0');if(isHost&&left<=0)end(true,'O tempo acabou sem ninguém tocar no professor!');if(isHost&&now>=nextFruitAt){spawnFruit();nextFruitAt=now+8000+Math.random()*7000}if(isHost&&now>=nextPillAt){spawnPill();nextPillAt=now+10000+Math.random()*8000}}
if(startedAt&&!finished&&self.alive){let dx=(keys['d']||keys['arrowright']?1:0)-(keys['a']||keys['arrowleft']?1:0),dy=(keys['s']||keys['arrowdown']?1:0)-(keys['w']||keys['arrowup']?1:0);if(dx||dy){let l=Math.hypot(dx,dy),sp=3.8*(self.speedUntil>now?2:1),nx=self.x+dx/l*sp,ny=self.y+dy/l*sp;if(safe(nx,self.y))self.x=nx;if(safe(self.x,ny))self.y=ny;if(isHost)lastMove={dx:Math.sign(dx),dy:Math.sign(dy)}}if(isHost&&pendingBlock){let currentCell={x:Math.floor(self.x/S),y:Math.floor(self.y/S)};if(currentCell.x!==pendingBlock.x||currentCell.y!==pendingBlock.y)activatePendingBlock()}players[self.id]=self;if(now-lastSend>85){lastSend=now;emit('state',{...self})}}
if(isHost&&startedAt&&!finished){Object.values(fruits).forEach(fruit=>{let hunter=Object.values(players).find(p=>p.id!==self.id&&p.alive&&Math.hypot(p.x-fruit.x,p.y-fruit.y)<18);if(hunter){hunter.hearts=(hunter.hearts??3)+1;delete fruits[fruit.id];emit('fruitCollected',{fruitId:fruit.id,playerId:hunter.id,hearts:hunter.hearts})}})}
if(isHost&&startedAt&&!finished){Object.values(pills).forEach(pill=>{let runner=Object.values(players).find(p=>p.alive&&Math.hypot(p.x-pill.x,p.y-pill.y)<18);if(runner){runner.speedUntil=now+6000;if(runner.id===self.id)self.speedUntil=runner.speedUntil;delete pills[pill.id];emit('pillCollected',{pillId:pill.id,playerId:runner.id,speedUntil:runner.speedUntil});if(runner.id===self.id)status.textContent='💊 Velocidade dobrada por 6 segundos!'}})}
if(isHost&&!finished){Object.values(players).filter(p=>p.id!==self.id&&p.alive).forEach(p=>{if(Math.hypot(p.x-self.x,p.y-self.y)<18)end(false,p.name+' alcançou o Ponto Dourado!')})}
bullets=bullets.filter(b=>{b.x+=b.dx*9;b.y+=b.dy*9;b.life--;let gx=Math.floor(b.x/S),gy=Math.floor(b.y/S);if(gx<=0||gy<=0||gx>=W-1||gy>=H-1||b.life<=0)return false;if(walls[gy][gx]){if(b.wallBreaker&&isHost){walls[gy][gx]=false;emit('wallDestroyed',{x:gx,y:gy});status.textContent='Parede destruída!'}return false}let block=blocks[blockKey(gx,gy)];if(block&&block.until>Date.now())return false;if(isHost&&!b.wallBreaker){let target=Object.values(players).find(p=>p.id!==self.id&&p.id!==b.owner&&p.alive&&Math.hypot(p.x-b.x,p.y-b.y)<18);if(target){target.hearts=Math.max(0,(target.hearts??3)-1);emit('damage',{id:target.id,hearts:target.hearts});if(target.hearts===0){target.alive=false;emit('eliminate',{id:target.id,reason:(players[b.owner]?.name||'Um caçador')+' acertou você três vezes!'})}return false}}return true});online.textContent=Math.max(0,Object.values(players).filter(p=>p.id!==self.id&&p.alive).length)+' caçadores ativos';}
function draw(){let me=self,ox=innerWidth/2-me.x,oy=innerHeight/2-me.y;ctx.fillStyle='#090b1a';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(ox,oy);for(let y=0;y<H;y++)for(let x=0;x<W;x++){ctx.fillStyle=walls[y][x]?'#313970':'#111633';ctx.fillRect(x*S,y*S,S-2,S-2);if(walls[y][x]){ctx.fillStyle='#5360ba';ctx.fillRect(x*S+4,y*S+4,S-10,5)}}Object.values(blocks).forEach(block=>{ctx.fillStyle='#f59e0b';ctx.fillRect(block.x*S+2,block.y*S+2,S-5,S-5);ctx.fillStyle='#fff3a3';ctx.fillRect(block.x*S+6,block.y*S+6,S-13,4)});Object.values(fruits).forEach(fruit=>{ctx.font='24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🍎',fruit.x,fruit.y)});Object.values(pills).forEach(pill=>{ctx.font='24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('💊',pill.x,pill.y)});ctx.textBaseline='alphabetic';Object.values(players).forEach(p=>{if(!p.alive)return;ctx.beginPath();ctx.fillStyle=p.id===self.id?p.color:(p.color||'#a78bfa');ctx.arc(p.x,p.y,p.id===self.id?12:9,0,Math.PI*2);ctx.fill();if((p.speedUntil||0)>Date.now()){ctx.strokeStyle='#22d3ee';ctx.lineWidth=3;ctx.stroke()}ctx.fillStyle='#fff';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(p.name,p.x,p.y-15);if(!isHost||p.id!==self.id){ctx.fillStyle='#ff7b94';ctx.font='12px system-ui';ctx.fillText('♥'.repeat(p.hearts??3),p.x,p.y+25)}});bullets.forEach(b=>{ctx.fillStyle=b.wallBreaker?'#22d3ee':'#ffdd57';ctx.beginPath();ctx.arc(b.x,b.y,b.wallBreaker?7:5,0,Math.PI*2);ctx.fill()});ctx.restore();requestAnimationFrame(loop)}
function loop(){update();draw()}loop();
})();
</script></body></html>`;
