-- Migration: Criar tabela para pontos extras por período e matrícula
CREATE TABLE IF NOT EXISTS public.student_period_extra_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES public.enrollments(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  period TEXT NOT NULL,
  extra_points NUMERIC DEFAULT 0,
  notes TEXT,
  teacher_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_enrollment_period UNIQUE (enrollment_id, period)
);

ALTER TABLE public.student_period_extra_points ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'student_period_extra_points' AND policyname = 'Allow all authenticated users access to student_period_extra_points'
  ) THEN
    CREATE POLICY "Allow all authenticated users access to student_period_extra_points"
    ON public.student_period_extra_points
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;
